Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -77,11 +77,11 @@ jobs:
 #            TF_ACTION_WORKING_DIR: '/production'
 #            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      run: terraform plan   # -input=false
+      run: terraform validate   # -input=false
       
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     - name: Terraform Plan Status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
 
       # On push to "main", build or change infrastructure according to Terraform configuration files
     - name: Terraform Apply
